openapi: 3.0.3
info:
  title: Renework API
  version: v1
  description: Course & application platform

servers:
  - url: https://localhost:5001
    description: Local dev

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /api/users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDto'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request

  /api/users/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginDto'
      responses:
        '200':
          description: JWT token
        '401':
          description: Unauthorized

  /api/users:
    get:
      summary: List users (admin only)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Array of users

  # …add /api/users/{id}, /api/courses, /api/appliedcourses, etc.

components:
  schemas:
    RegisterDto:
      type: object
      properties:
        name:     { type: string }
        email:    { type: string, format: email }
        password: { type: string }
        role:     { type: string }
      required: [name, email, password, role]

    LoginDto:
      type: object
      properties:
        email:    { type: string, format: email }
        password: { type: string }
      required: [email, password]

    # …add Course, AppliedCourse, Application, CourseReview schemas here
